name: test
on:
  push

jobs:
  coverage:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install
        run: npm install
      - name: test
        run: npm run test
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
